[project]
name = "eris_verifier"
version = "0.1.0"
dependencies = [
    'pytest'
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.uv.scripts]
test = "pytest test_suite.py"
